server:
  port: 8081
  address: 0.0.0.0
spring:
  mvc:
    static-path-pattern: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/miooyuki_docsys?serverTimezone=Asia/Shanghai"
    username: "root"
    password: "123456"
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/templates/
    suffix: .html
